name: ghibli_redux
description: Mobile client for The Studio Ghibli API.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  # Base
  logger: 0.9.4

  # DI
  get_it: 5.0.6

  # Model
  freezed_annotation: 0.12.0
  json_annotation: 3.1.1

  # Network
  dio: 3.0.10
  retrofit: 1.3.4+1

  # State management
  redux: 4.0.0+3
  flutter_redux: 0.7.0

  # UI
  cupertino_icons: 1.0.0
  intl: 0.16.1
  easy_localization: 2.3.3
  fluttertoast: 7.1.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.10.11
  freezed: 0.12.7
  json_serializable: 3.5.1
  retrofit_generator: 1.4.1+3


flutter:
  uses-material-design: true